### ISSUE TITLE
Link back to FAC

### ISSUE THREAD

**Issue by rub1e** [foundersandcoders/techforbetter-website#108]
As far as I can see, the T4B site doesn't link back to the FAC site at all, and vice versa

cf https://github.com/foundersandcoders/our-site/issues/509

**Comment by sima-qian** [comment]
As far as I recall, one of the answers in the FAQ section linked to the main site, but we recently removed a number of questions for clarity.

I can add a link in the _About_ section, or do you think 'Founders & Coders' on the splash page could be a link?
