### ISSUE TITLE
Questionnaire: first draft

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/techforbetter-website#43]
Application for TECH FOR GOOD PRODUCT DEVELOPMENT PROGRAMME

- Your name
- You email address
- Your organisation name
- Are you representing
  - Yourself
  - An unregistered group
  - A registered charity
  - A social enterprise
  - A public sector organisation
  - A company
- Briefly summarise the user need you are trying to meet
- Briefly summarise the history of the project so far
- Briefly summarise any market research that you have already done
- Give examples of comparable projects that could inspire this one
- Why would a free MVP be beneficial to you and what plans do you have after it is completed?
- Have you ever worked on a digital project before and do you have any experience of building MVPs or of agile software development processes ?
- Are you familiar with the concept of a “product owner”?
- You will need to be engaged for an average of 8 hours per week throughout the month of the build. Please confirm the months in which you are available:
  - October
  - November
  - December
  - January

**Comment by arrested-developer** [comment]
Should q10 be split into two smaller questions?

**Comment by thejoefriel** [comment]
Do we need to elaborate on the product owner question? At the moment maybe confusing as to how much they are meant to put in here (is a yes/no sufficient or do they need to give their understanding of one)

**Comment by thejoefriel** [comment]
Should we have a question about job title? Do we need a sense as to level of person who would be leading from their side on the project?
