### ISSUE TITLE
Add links to Portfolio apps-2

### ISSUE THREAD

**Issue by sunuwars** [foundersandcoders/techforbetter-website#47]
For me when I think some one offering free tech for good , I think it's going to be a free new website.

In the portfolio, the apps had no link(if we are allowed to share it?), I personally tried to find the apps to see how and they work (googled) but I found only two of them and despite having some knowledge of how they should look, I couldn't find the remaining ones!

I think the problem could be people not being able to have ideas how they could benefit from tech for good app.

**Comment by sunuwars** [comment]
this has been addressed.

**Comment by sima-qian** [comment]
Fixed in #52
