### ISSUE TITLE
Rebuild website from scratch?

### ISSUE THREAD

**Issue by sima-qian** [foundersandcoders/techforbetter-website#49]
Given the amount of CSS (~3500 lines 😱 ) and other complexities, it seems to me to be just as time-consuming to understand the website enough to make small changes as to take a stripped-down html skeleton and rebuild completely. Thoughts?

**Comment by MissArray** [comment]
Haven't looked at the CSS, but just heard that it was originally based on a ready-made template. Of course libraries and templates are widely used by professional developers, but I wonder whether templates might not be the best way of demonstrating that we can actually code? So, perhaps @sima-qian's suggestion is good, also for that reason - provided that it's feasible in the available time?

**Comment by sofer** [comment]
Rebuilding the website would be a great side project for reading week or while people are job hunting at the end of the course.

**Comment by MissArray** [comment]
Nitpicking:

* Nit  No. 1: We're not using serial commas elsewhere on the website, so in
'What is a mobile web app?'
'on a computer, `tablet or` smartphone.'

* Nit No. 2:
Redundant 'the organisation'
'Do I have to be a UK-based non-profit?'
'or where `it` is based.'

* A somewhate larger nit:
All running text is currently centred. Is that a good idea? In
conventional, i.e. analogue, typography, the general rule of thumb is,
centre (optionally) captions, headings, subheadings, but not running text.
It's less readable and everything's emphasised.
Did anyone try justifying the content in centred block quotes to see
whether the visual end result might be better/worse?

**Comment by sima-qian** [comment]
New website merged into master at #76
