### ISSUE TITLE
Old image previews when sharing

### ISSUE THREAD

**Issue by rub1e** [foundersandcoders/techforbetter-website#57]
![screenshot 2018-07-24 at 17 50 00](https://user-images.githubusercontent.com/11595920/43153878-692e8fc2-8f6a-11e8-9e97-d2f96485bb7f.png)

Old image appears when sharing on Facebook - mentions pitch day in June and old strapline

**Comment by sima-qian** [comment]
Should be fixed in #59, checked on FaceBook for developers -- updated image showing there. Not sure if showing in the real world?

**Comment by rub1e** [comment]
Fantastic work @sima-qian !
