### ISSUE TITLE
Link to grow app 🌱

### ISSUE THREAD

**Issue by emilyb7** [foundersandcoders/techforbetter-website#62]
Hi!

Love the website 🌈 

Probably I'm the only person to notice/care, I just noticed that the link in the modal for Grow points to the welcome to CAMHs project (which, by the way, is excellent and should probably feature here too.)

Anyway, Grow is supposed to have its own domain (https://www.growgoals.co.uk/) but I just checked it out and it's not working (I think no one is paying for the domain) :'( --- maybe remove the link? remove Grow altogether? Or you could point to https://polar-dawn-55555.herokuapp.com/login, which is an older version of the app!

**Comment by sbinlondon** [comment]
@sofer @lucymk Is there another project we can showcase to replace Grow, or are you happy pointing to the Heroku app?

**Comment by emilyb7** [comment]
Grow is back at https://growgoals.co/
