### ISSUE TITLE
Vertical line on top of page in MS Edge

### ISSUE THREAD

**Issue by MissArray** [foundersandcoders/techforbetter-website#95]
The vertical line (see screenshot) seems to persist in Edge (Windows 10 platform):

![fac-student-website-master-edge](https://user-images.githubusercontent.com/33687551/43676023-212445da-97e1-11e8-94c1-0d469d128baf.PNG)

**Comment by sima-qian** [comment]
Thanks for raising this issue - I have a Mac so unfortunately had no way to check how the site looks in Edge.

It may be a problem with z-indexing. At the moment, the div that gives the vertical line has `z-index: -1` (main.css, line 51). Could you try giving `header` or `#header-background` the property `z-index: 0` and see if the vertical line disappears in the header?

**Comment by MissArray** [comment]
Setting the header's z-index to 0 fixes the issue. Will add it to the LinksToLogos branch.

**Comment by sima-qian** [comment]
That's brilliant, thanks!

**Comment by MissArray** [comment]
Would you like to close this issue, once the commit has been approved?

**Comment by sima-qian** [comment]
Sure thing
